# Generated by Django 6.0.5 on 2026-05-20 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('bidang_studi', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil_guru/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50, unique=True)),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_binaan', to='core.guru')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='KepalaSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True, verbose_name='NIP')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil_kepsek/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kepsek_core_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktor Kepala Sekolah',
                'verbose_name_plural': 'Profil Kepala Sekolah',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='KeuanganSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tagihan', models.CharField(max_length=100)),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status_lunas', models.BooleanField(default=False)),
                ('tanggal_tagihan', models.DateField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.siswa')),
            ],
            options={
                'verbose_name': 'Keuangan Siswa',
                'verbose_name_plural': 'Keuangan Siswa',
            },
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True, verbose_name='NIP/Id Staf')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('bagian', models.CharField(choices=[('TU', 'Tata Usaha / Administrasi'), ('KEU', 'Bendahara Keuangan'), ('PERPUS', 'Perpustakaan')], default='TU', max_length=20)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staf_core_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktor Staf',
                'verbose_name_plural': 'Profil Staf Sekolah',
            },
        ),
        migrations.CreateModel(
            name='WaliMurid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wali_core_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktor Wali Murid',
                'verbose_name_plural': 'Profil Wali Murid',
            },
        ),
        migrations.AddField(
            model_name='siswa',
            name='wali',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daftar_anak', to='core.walimurid'),
        ),
    ]
