# Generated by Django 6.0.5 on 2026-05-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siswa_nama_orang_tua_siswa_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kepalasekolah',
            old_name='foto',
            new_name='foto_kepsek',
        ),
    ]
