# Generated by Django 6.0.5 on 2026-05-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_foto_kepalasekolah_foto_kepsek'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daftar_siswa', to='core.kelas'),
        ),
    ]
