# Generated by Django 6.0.5 on 2026-06-02 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siswa_kelas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(max_length=20, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='guru',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guru_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keuangansiswa',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keuangansiswa_set', to='core.siswa'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=20, unique=True, verbose_name='NISN'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
