# Generated by Django 6.0.5 on 2026-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_guru_nip_alter_guru_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walimurid',
            options={'verbose_name': 'Aktor Wali Murid', 'verbose_name_plural': 'Wali'},
        ),
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil_siswa/'),
        ),
    ]
