# Generated by Django 6.0.5 on 2026-06-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_walimurid_options_siswa_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staf",
            options={
                "verbose_name": "Aktor Staf",
                "verbose_name_plural": "Staf Akademik",
            },
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="nama_orang_tua",
        ),
    ]
