# Generated by Django 6.0.5 on 2026-05-20 02:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_kegiatan', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('waktu', models.CharField(help_text='Contoh: 08:00 - Selesai', max_length=100)),
                ('lokasi', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Agenda Sekolah',
            },
        ),
        migrations.CreateModel(
            name='DokumenUnduhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dokumen_akademik/')),
            ],
            options={
                'verbose_name': 'Dokumen Unduhan',
                'verbose_name_plural': 'Dokumen Unduhan',
            },
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='galeri/%Y/%m/%d/')),
                ('kategori', models.CharField(choices=[('fasilitas', 'Fasilitas & Lab'), ('kegiatan', 'Kegiatan Belajar'), ('ekstra', 'Ekstrakurikuler')], default='kegiatan', max_length=20)),
                ('tanggal_kegiatan', models.DateField(help_text='Tanggal dokumentasi acara/fasilitas diambil')),
            ],
            options={
                'verbose_name': 'Galeri Sekolah',
                'verbose_name_plural': 'Galeri Foto Kegiatan',
                'ordering': ['-tanggal_kegiatan'],
            },
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_keahlian', models.CharField(choices=[('TKJ', 'Teknik Komputer Jaringan'), ('RPL', 'Rekayasa Perangkat Lunak')], max_length=3)),
                ('mata_pelajaran', models.CharField(max_length=255)),
                ('alokasi_waktu', models.CharField(help_text='Contoh: 6 Jam / Minggu', max_length=100)),
                ('ruangan', models.CharField(help_text='Contoh: Lab Coding Alfa', max_length=100)),
            ],
            options={
                'verbose_name': 'Jadwal Pelajaran',
                'verbose_name_plural': 'Jadwal Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='KepalaSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150)),
                ('sambutan', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='kepsek/')),
                ('ttd', models.ImageField(blank=True, null=True, upload_to='kepsek/ttd/')),
            ],
            options={
                'verbose_name': 'Kepala Sekolah',
                'verbose_name_plural': 'Kepala Sekolah (Profil)',
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('isi', models.TextField()),
                ('tanggal', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='PpdbGelombang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(help_text='Contoh: Gelombang I (Reguler)', max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('biaya', models.IntegerField(default=0, help_text='Tulis nominal saja tanpa titik/koma. Contoh: 250000')),
                ('is_aktif', models.BooleanField(default=True)),
                ('deskripsi', models.TextField(blank=True, help_text='Rincian alur atau berkas tambahan gelombang ini', null=True)),
            ],
            options={
                'verbose_name': 'Gelombang PPDB',
                'verbose_name_plural': 'Gelombang Seleksi PPDB',
            },
        ),
        migrations.CreateModel(
            name='PpdbSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brosur_pdf', models.FileField(blank=True, null=True, upload_to='ppdb/brosur/')),
                ('informasi_tambahan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pengaturan PPDB',
                'verbose_name_plural': 'Pengaturan PPDB',
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('juara', models.CharField(help_text='Contoh: Juara 1 Emas', max_length=100)),
                ('nama_lomba', models.CharField(help_text='Contoh: Lomba Karya Tulis Ilmiah Nasional', max_length=200)),
                ('nama_siswa', models.CharField(help_text='Contoh: Ahmad Dhani / Tim Teknik Komputer', max_length=150)),
                ('tingkat', models.CharField(help_text='Contoh: Tingkat Provinsi / Nasional', max_length=100)),
            ],
            options={
                'verbose_name': 'Prestasi Sekolah',
                'verbose_name_plural': 'Prestasi Akademik & Non-Akademik',
            },
        ),
        migrations.CreateModel(
            name='StatistikSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_studi', models.CharField(default='Statistik Utama Sekolah', editable=False, max_length=50)),
            ],
            options={
                'verbose_name': 'Statistik Sekolah',
                'verbose_name_plural': 'Statistik Sekolah',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to='berita/%Y/%m/%d/')),
                ('keterangan', models.TextField()),
                ('tanggal_post', models.DateField()),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Berita Sekolah',
            },
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nisn', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'NISN harus berupa 10 digit angka.')])),
                ('asal_sekolah', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Format nomor HP tidak valid.')])),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pendaftaran Siswa Baru',
                'ordering': ['-created_at'],
            },
        ),
    ]
