# Generated by Django 6.0.5 on 2026-05-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_publik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekstrakurikuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: IT Club & Robotics', max_length=150)),
                ('deskripsi', models.TextField(help_text='Deskripsi singkat kegiatan ekstrakurikuler.')),
                ('icon', models.CharField(choices=[('fa-code', 'Pemrograman / IT'), ('fa-camera', 'Fotografi / Multimedia'), ('fa-futbol', 'Olahraga (Bola)'), ('fa-basketball', 'Olahraga (Basket)'), ('fa-music', 'Seni & Musik'), ('fa-leaf', 'Alam / Pramuka'), ('fa-microphone-lines', 'Debat / Public Speaking'), ('fa-palette', 'Seni Rupa / Desain'), ('fa-book-open', 'Literasi / Perpustakaan'), ('fa-shield-halved', 'PMR / Kesehatan'), ('fa-robot', 'Robotika / IoT'), ('fa-chess', 'Catur / Strategi')], default='fa-star', help_text='Pilih ikon Font Awesome yang mewakili ekskul ini.', max_length=50)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil di halaman. Angka lebih kecil tampil lebih dulu.')),
                ('is_aktif', models.BooleanField(default=True, help_text='Centang jika ekskul ini aktif dan ingin ditampilkan.')),
            ],
            options={
                'verbose_name': 'Ekstrakurikuler',
                'verbose_name_plural': 'Daftar Ekstrakurikuler',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='KontakSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telepon', models.CharField(help_text='Contoh: (0376) 23456', max_length=50)),
                ('email', models.EmailField(help_text='Contoh: info@siakadpro.sch.id', max_length=254)),
                ('alamat', models.TextField(help_text='Alamat lengkap sekolah. Contoh: Jl. Pendidikan No. 123, Lombok Timur, NTB')),
                ('website', models.URLField(blank=True, help_text='URL website resmi (opsional)', null=True)),
                ('wa', models.CharField(blank=True, help_text='Nomor WhatsApp (opsional). Contoh: 62817xxxxxxx', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Kontak Sekolah',
                'verbose_name_plural': 'Kontak Sekolah (Sidebar Profil)',
            },
        ),
        migrations.CreateModel(
            name='LayananAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('program', 'Program Unggulan / Jurusan'), ('fasilitas', 'Fasilitas Utama')], default='program', help_text='Pilih apakah ini Program Keahlian atau Fasilitas.', max_length=10)),
                ('nama', models.CharField(help_text='Contoh: Teknik Komputer & Jaringan (TKJ) / Laboratorium Komputer Modern', max_length=200)),
                ('deskripsi', models.TextField(help_text='Penjelasan singkat mengenai program atau fasilitas ini.')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil (angka lebih kecil = tampil lebih dulu).')),
            ],
            options={
                'verbose_name': 'Layanan Akademik & Sarana',
                'verbose_name_plural': 'Layanan Akademik & Sarana',
                'ordering': ['jenis', 'urutan'],
            },
        ),
    ]
