# Generated by Django 6.0.5 on 2026-06-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_publik', '0002_ekstrakurikuler_kontaksekolah_layananakademik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontaksekolah',
            options={'verbose_name': 'Kontak Sekolah', 'verbose_name_plural': 'Kontak Sekolah'},
        ),
    ]
