# Generated by Django 6.0.5 on 2026-06-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_publik", "0003_alter_kontaksekolah_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jadwalpelajaran",
            options={
                "verbose_name": "Jadwal Pelajaran",
                "verbose_name_plural": "Jadwal Pelajaran Publik",
            },
        ),
    ]
