# Generated by Django 6.0.5 on 2026-05-20 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='AdministrasiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tagihan', models.CharField(default='SPP Bulanan', help_text='Contoh: SPP, Uang Gedung, Ujian', max_length=100)),
                ('jumlah_tagihan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Lunas', 'Lunas / Terverifikasi'), ('Tertunggak', 'Belum Membayar')], default='Tertunggak', max_length=15)),
                ('tanggal_perubahan', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrasi', to='core.siswa')),
            ],
            options={
                'verbose_name': 'Administrasi Keuangan Siswa',
                'verbose_name_plural': 'Administrasi Keuangan Siswa',
            },
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('kelas', models.CharField(max_length=50)),
                ('ruangan', models.CharField(blank=True, max_length=50, null=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_guru', to='core.guru')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_pelajaran', to='akademik.matapelajaran')),
            ],
            options={
                'verbose_name': 'Jadwal Pelajaran',
                'verbose_name_plural': 'Jadwal Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='JurnalMengajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('materi_pembahasan', models.TextField(help_text='Tuliskan ringkasan materi yang diajarkan')),
                ('kendala_kbm', models.TextField(blank=True, help_text='Tuliskan kendala siswa atau kelas jika ada', null=True)),
                ('tindak_lanjut', models.TextField(blank=True, null=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_jadwal', to='akademik.jadwalpelajaran')),
            ],
            options={
                'verbose_name': 'Jurnal Mengajar',
                'verbose_name_plural': 'Jurnal Mengajar',
            },
        ),
        migrations.CreateModel(
            name='KepalaSekolahProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nip', models.CharField(blank=True, max_length=30, null=True, verbose_name='NIP')),
                ('bio', models.TextField(blank=True, help_text='Visi misi atau kutipan singkat pimpinan', null=True)),
                ('foto_kepsek', models.ImageField(blank=True, help_text='Upload foto resmi untuk dashboard', null=True, upload_to='profil_kepsek/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kepala_sekolah_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Kepala Sekolah',
                'verbose_name_plural': 'Profil Kepala Sekolah',
            },
        ),
        migrations.CreateModel(
            name='MateriAjar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('file_materi', models.FileField(blank=True, help_text='Upload PDF/PPT/Word Dokumen', null=True, upload_to='materi_ajar/')),
                ('link_external', models.URLField(blank=True, help_text='Link opsional (Misal: Google Drive/YouTube)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guru')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matapelajaran')),
            ],
            options={
                'verbose_name': 'Materi Ajar',
                'verbose_name_plural': 'Materi Ajar',
            },
        ),
        migrations.CreateModel(
            name='NilaiRapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_tugas', models.IntegerField(default=0)),
                ('nilai_uts', models.IntegerField(default=0)),
                ('nilai_uas', models.IntegerField(default=0)),
                ('nilai_angka', models.IntegerField(default=0, help_text='Nilai Akhir Rapor gabungan')),
                ('keterangan', models.TextField(blank=True, help_text='Deskripsi capaian kompetensi / kemajuan belajar', null=True)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.siswa')),
            ],
            options={
                'verbose_name': 'Nilai Rapor',
                'verbose_name_plural': 'Nilai Rapor',
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('jadwal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.jadwalpelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_siswa', to='core.siswa')),
            ],
            options={
                'verbose_name': 'Presensi',
                'verbose_name_plural': 'Presensi',
            },
        ),
        migrations.CreateModel(
            name='SambutanKepsek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sambutan', models.TextField(help_text='Tuliskan kata sambutan resmi untuk halaman profil publik')),
                ('foto', models.ImageField(blank=True, help_text='Upload foto resmi', null=True, upload_to='kepsek/')),
                ('ttd', models.ImageField(blank=True, help_text='Upload tanda tangan digital transparan (PNG)', null=True, upload_to='kepsek/ttd/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_sekolah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sambutan_profile', to='core.kepalasekolah', verbose_name='Kepala Sekolah')),
            ],
            options={
                'verbose_name': 'Sambutan Kepala Sekolah',
                'verbose_name_plural': 'Sambutan Kepala Sekolah',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nip', models.CharField(blank=True, max_length=30, null=True, verbose_name='NIP/NIY')),
                ('jabatan', models.CharField(choices=[('Kaur Tata Usaha', 'Kepala Urusan Tata Usaha'), ('Staff Administrasi', 'Staff Administrasi Siswa'), ('Staff Kepegawaian', 'Staff Administrasi Kepegawaian'), ('Operator Dapodik', 'Operator Sistem / Dapodik')], default='Staff Administrasi', max_length=50)),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('foto_staf', models.ImageField(blank=True, help_text='Upload foto resmi staf', null=True, upload_to='profil_staf/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staf_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Staff Tata Usaha',
                'verbose_name_plural': 'Profil Staff Tata Usaha',
            },
        ),
        migrations.CreateModel(
            name='TugasKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('Tugas', 'Tugas Harian'), ('Kuis', 'Kuis Online')], max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('batas_waktu', models.DateTimeField(help_text='Deadline pengumpulan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guru')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matapelajaran')),
            ],
            options={
                'verbose_name': 'Tugas & Kuis',
                'verbose_name_plural': 'Tugas & Kuis',
            },
        ),
    ]
