# Generated by Django 6.0.5 on 2026-05-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugaskuis',
            name='jadwal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tugas_kelas', to='akademik.jadwalpelajaran'),
        ),
    ]
