# Generated by Django 6.0.5 on 2026-05-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_tugaskuis_jadwal'),
        ('core', '0004_siswa_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrasisiswa',
            name='jenis_tagihan',
            field=models.CharField(default='SPP Bulanan', max_length=100),
        ),
        migrations.AlterField(
            model_name='jadwalpelajaran',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kelas', to='core.kelas', verbose_name='Kelas'),
        ),
        migrations.AlterField(
            model_name='jurnalmengajar',
            name='kendala_kbm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kepalasekolahprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kepalasekolahprofile',
            name='foto_kepsek',
            field=models.ImageField(blank=True, null=True, upload_to='profil_kepsek/'),
        ),
        migrations.AlterField(
            model_name='kepalasekolahprofile',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='materiajar',
            name='file_materi',
            field=models.FileField(blank=True, null=True, upload_to='materi_ajar/'),
        ),
        migrations.AlterField(
            model_name='materiajar',
            name='link_external',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nilairapor',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sambutankepsek',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='kepsek/'),
        ),
        migrations.AlterField(
            model_name='sambutankepsek',
            name='sambutan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sambutankepsek',
            name='ttd',
            field=models.ImageField(blank=True, null=True, upload_to='kepsek/ttd/'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='foto_staf',
            field=models.ImageField(blank=True, null=True, upload_to='profil_staf/'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
