# Generated by Django 6.0.5 on 2026-06-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_alter_administrasisiswa_jenis_tagihan_and_more'),
        ('core', '0005_alter_guru_nip_alter_guru_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_jawaban', models.FileField(upload_to='jawaban_siswa/%Y/%m/')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dikirim_at', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_at', models.DateTimeField(auto_now=True)),
                ('nilai', models.IntegerField(blank=True, help_text='Nilai yang diberikan guru (0–100)', null=True)),
                ('catatan_guru', models.TextField(blank=True, help_text='Catatan / feedback dari guru', null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_tugas', to='core.siswa')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='akademik.tugaskuis')),
            ],
            options={
                'verbose_name': 'Jawaban Siswa',
                'verbose_name_plural': 'Jawaban Siswa',
                'ordering': ['-dikirim_at'],
                'unique_together': {('tugas', 'siswa')},
            },
        ),
    ]
