# Generated by Django 6.0.5 on 2026-06-04 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_jawabansiswa'),
        ('core', '0005_alter_guru_nip_alter_guru_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiPerilaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=20)),
                ('tahun_ajaran', models.CharField(default='2025/2026', max_length=10)),
                ('kedisiplinan', models.IntegerField(default=0, help_text='Nilai 0-100: ketepatan waktu, kepatuhan aturan')),
                ('keaktifan', models.IntegerField(default=0, help_text='Nilai 0-100: partisipasi aktif di kelas')),
                ('kerja_sama', models.IntegerField(default=0, help_text='Nilai 0-100: kemampuan bekerja sama dengan teman')),
                ('sopan_santun', models.IntegerField(default=0, help_text='Nilai 0-100: sikap dan tata krama')),
                ('nilai_perilaku', models.IntegerField(default=0, help_text='Rata-rata otomatis dari 4 aspek di atas')),
                ('predikat', models.CharField(choices=[('A', 'Sangat Baik'), ('B', 'Baik'), ('C', 'Cukup'), ('D', 'Perlu Bimbingan')], default='B', max_length=1)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dibuat_at', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_perilaku_guru', to='core.guru')),
                ('mata_pelajaran', models.ForeignKey(blank=True, help_text='Kosongkan jika penilaian bersifat umum', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_perilaku_mapel', to='akademik.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_perilaku', to='core.siswa')),
            ],
            options={
                'verbose_name': 'Nilai Perilaku Siswa',
                'verbose_name_plural': 'Nilai Perilaku Siswa',
                'unique_together': {('siswa', 'guru', 'semester', 'tahun_ajaran')},
            },
        ),
    ]
