# Generated by Django 6.0.5 on 2026-06-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_nilaiperilaku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NilaiPerilaku',
        ),
    ]
