# Generated by Django 6.0.5 on 2026-06-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_delete_nilaiperilaku'),
        ('core', '0005_alter_guru_nip_alter_guru_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilairapor',
            name='nilai_perilaku',
            field=models.IntegerField(default=0, help_text='Rata-rata nilai perilaku siswa dari semua guru (0-100)'),
        ),
        migrations.AlterField(
            model_name='jawabansiswa',
            name='nilai',
            field=models.IntegerField(blank=True, help_text='Nilai yang diberikan guru (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='nilairapor',
            name='nilai_angka',
            field=models.IntegerField(default=0, help_text='Nilai Akhir = (tugas*35%) + (uts*25%) + (uas*25%) + (perilaku*15%)'),
        ),
        migrations.CreateModel(
            name='NilaiPerilaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(help_text='Tanggal sesi mengajar')),
                ('kategori', models.CharField(choices=[('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], help_text='Penilaian perilaku siswa pada sesi ini', max_length=10)),
                ('catatan', models.CharField(blank=True, help_text='Catatan singkat opsional dari guru', max_length=255, null=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_perilaku', to='core.guru')),
                ('jadwal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perilaku_jadwal', to='akademik.jadwalpelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_perilaku', to='core.siswa')),
            ],
            options={
                'verbose_name': 'Nilai Perilaku Siswa',
                'verbose_name_plural': 'Nilai Perilaku Siswa',
                'ordering': ['-tanggal'],
                'unique_together': {('siswa', 'guru', 'jadwal', 'tanggal')},
            },
        ),
    ]
